### ISSUE TITLE
Handle logged-out users better

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#107]
- [x] The events overview page and details page should be available to everyone.
- [x] When a user tries to access the restricted pages(e.g https://translate.wordpress.org/events/new/), we should direct them to the login page and redirect them back.
- [x] On an event page, the attend button should become a login to attend button with a redirect.

**Comment by amieiro** [comment]
Currently, the events overview page and details page are available to everyone.

![image](https://github.com/WordPress/wporg-gp-translation-events/assets/1667814/a49ca502-e75a-4092-a702-516384eff69c)

![image](https://github.com/WordPress/wporg-gp-translation-events/assets/1667814/d5e74222-76b4-4419-b628-8b664b03c514)
