### ISSUE TITLE
Refactor the code that retrieves active events the user is attending

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#117]
@psrpinto [said](https://github.com/WordPress/wporg-gp-translation-events/pull/114/files#r1496047478): 
> I think maybe we should consider refactoring [the code that retrieves active events the user is attending](https://github.com/WordPress/wporg-gp-translation-events/blob/trunk/includes/translation-listener.php#L69-L70) to something reusable, as I noticed we need that in several places.
> 
> If we would do that, we would automatically get caching for the query that retrieves active events, as that can be an expensive query.

**Comment by psrpinto** [comment]
This is now fixed since the introduction of the event repository.
