### ISSUE TITLE
Highlight first time contributors in the stats summary

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#166]
In the stats summary text, we could decide to highlight the number of first time contributors.

**Comment by akirk** [comment]
We discussed this and agree that we want to determine new contributors by looking at their first translation. If it happened in the last 24hrs before the event start, they are considered a new contributor.
```sql
SELECT MIN(date_added) FROM `translate_translations` WHERE `user_id` = 123
```

The reasoning behind the 24hrs before event start is that they might try translating something before the event but then should still count as a new contributor.

**Comment by akirk** [comment]
Highlight new contributors, maybe like this:
![Screenshot 2024-03-21 at 11 25 37](https://github.com/WordPress/wporg-gp-translation-events/assets/203408/4ff02b13-fa83-4a51-a83c-d1e6f1cd7595)
