### ISSUE TITLE
Update UI to reflect the Renaming of Attend to RSVP

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#176]

**Comment by amieiro** [comment]
I've been thinking about this change, and I am not sure about it. 

In meetup.com, if you take a look to a future event with the `en-US`interface, they use:
- the `Attend` verb to assist to the future event.
- The `Attendees` noun for the list of future assistants.

![image](https://github.com/WordPress/wporg-gp-translation-events/assets/1667814/9daa6b86-db5c-4932-b2bd-6ffbf0ffe5e5)

[RSVP](https://en.wikipedia.org/wiki/RSVP) means "Respond, if it pleases you", or just "Please respond", so it could be understood as a request for a confirmation. IMHO, I understand better the "Attend" option and not the RSVP option. What do you think about?

**Comment by akirk** [comment]
We agreed to close this so that we don't call this rsvp.
