### ISSUE TITLE
Allow to have co-hosts

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#178]
Allow main host to add other users as co-hosts so that the co-hosts can also manage the event.

**Comment by trymebytes** [comment]
Will there be a limit to the number of the co-hosts that can be added? Are going to implement this by adding the event_id to the user meta or would we make use of the attendees table for this?

**Comment by psrpinto** [comment]
Something that has been on my mind lately is that I think we could generalise cohosts into a permissions system.

From what I gather, a cohost is a user who can manage the event. I'm assuming "manage" means they have permissions to do all actions on an event, for example:

- Edit title, description, start, end, etc
- Delete the event
- (Hypothetically, in the future) Invite other users to the event

I can image that in the future we could want to be able to assign only some of the permissions to attendees of the event, for example "Invite other users", but not other permissions, like delete the event.

In addition to this, I'm guessing that we want to show in the UI who are the cohosts of an event, so we also need to track who are the cohosts of an event.

To me this feels like two different concepts:

1. Who can do what on an event
2. Who is a cohost of an event

So I think we could separate those concepts in the code/data too. One way to do this would be as follows.

---

The attendees table would have a column for each permission:

- `event_id`
- `user_id`
- `can_edit`
- `can_delete`
- `can_invite`
- etc...

The postmeta of an event has the list of user ids who are cohosts.

Finally, cohosts get all the permissions by default.

So whenever we need to ensure a user can do an operation (e.g. delete the event), we would do something like:

```php
$event_id = ...;
$user_id = ...;

$event_repository = new Event_Repository();
$attendee_repository = new Event_Repository();

$event = $this->event_repository->get_event( $event_id );
$attendee = $this->attendee_repository->get_attendee( $event_id, $user_id );

if ( $event->is_cohost( $user_id ) || $attendee->can_delete() ) {
    // Delete the event.
}
```

**Comment by amieiro** [comment]
I think we should allow adding "infinite" co-hosts to an event. 
I don't know if it makes sense to have different profiles for the co-host role. Maybe it is simpler to allow all the actions to the co-host except the event deletion, that should be made by the creator or by an administrator.
With this approach, we can have one extra field in the `{$gp_table_prefix}event_attendees` table created in the https://github.com/WordPress/wporg-gp-translation-events/pull/172 PR to store if the attendee is a co-host or not. Could we have a co-host not attending to the event? Does it make sense?
If we need to have different roles, we need an extra table with the roles and an extra field in the `event_attendees` table, with a 1-n relation.

**Comment by psrpinto** [comment]
Some discussion relevant to this happened in #172. In the end we went with having an `is_host` field in the attendees table.
