### ISSUE TITLE
Set the contributor flag on an the attendee when the user contributes a translation

### ISSUE THREAD

**Issue by psrpinto** [WordPress/wporg-gp-translation-events#196]
- [ ] Set `contributor` to true in the attendees table when the user adds or reviews a translation
- [ ] `Database::import_legacy_attendees()` must set the `contributor` flag

**Comment by akirk** [comment]
It'd be enough if this is done after the event is over since we mostly want to use the field for post-event stats.

**Comment by psrpinto** [comment]
Closing since no longer relevant as in #172 it was decided to not store `is_contributor` (for now, at least).
