### ISSUE TITLE
Use is_host from attendees table instead of post_author to determine who is a host

### ISSUE THREAD

**Issue by psrpinto** [WordPress/wporg-gp-translation-events#199]
In #172 we made it so that the attendees table has an `is_host` field. However, this field is not yet being used everywhere to determine who is the host of an event.

We need to go over all places in the code where we use the `post_author`(or `$event->author_id()`)  to tell who is the host of an event, and change it so that it uses `is_host` from the attendees table instead.

**Comment by psrpinto** [comment]
Related to #178

**Comment by akirk** [comment]
@amieiro this will solve the permissions problem you'll be facing in #200

**Comment by psrpinto** [comment]
I intended to take this issue, but I noticed it would need code that is being introduced in #200, so I think we should wait for #200 to be merged before tackling this one.

It could also be that #200 actually also fixes this issue. Once #200 is merged, we should check whether this issue is still relevant or not.

**Comment by trymebytes** [comment]
@psrpinto is it okay to close this?

**Comment by psrpinto** [comment]
I'm currently double-checking this, will close once I've confirmed it.

**Comment by psrpinto** [comment]
I've now confirmed this can be closed.
