### ISSUE TITLE
Improve Attendee/Hosts code

### ISSUE THREAD

**Issue by psrpinto** [WordPress/wporg-gp-translation-events#208]
I think there's room for improvement on the Attendee/Host thing is currently represented in code. An [example](https://github.com/WordPress/wporg-gp-translation-events/pull/206#discussion_r1565866331) is:

<img width="793" alt="Screenshot 2024-04-15 at 16 32 17" src="https://github.com/WordPress/wporg-gp-translation-events/assets/550401/8be26dc1-6f09-4aad-9854-53b466345f30">

**Comment by trymebytes** [comment]
@psrpinto I think it's okay to close this, since the PR has been merged.

**Comment by psrpinto** [comment]
I created this issue because I agreed with the suggestion but I preferred to not address it in that PR, as I think fixing this will require lots of changes. I'm still planning on addressing this soon, so I would keep it open, if that's ok with you.

**Comment by trymebytes** [comment]
Oh, that's okay! Thanks!
