### ISSUE TITLE
Show number of attendees and contributors

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#216]
Users should be able to see the number of attendees at a glance when viewing the event page.
![Screenshot 2024-04-17 at 12 56 54](https://github.com/WordPress/wporg-gp-translation-events/assets/2834132/4943fba4-0af0-4405-ad43-fbcd7dbe72e2)

**Comment by akirk** [comment]
Nice, this would be useful indeed. Maybe we can do it without parenthesis and just a smaller font.
