### ISSUE TITLE
Performance improvements for event details page

### ISSUE THREAD

**Issue by psrpinto** [WordPress/wporg-gp-translation-events#225]
I noticed that the event details page takes a few seconds to load, for [Yoast Contributor day 2024 – April edition](https://translate.wordpress.org/events/yoast-contributor-day-2024-april-edition/).

We should look into what the culprits are and see if we can optimise it.

**Comment by psrpinto** [comment]
I looked into the query performance in production using [query monitor](https://wordpress.org/plugins/query-monitor/). For the "Yoast Contributor Day" event, the page takes around 6 seconds to load and query time amounts for around 3.3 seconds.

`is_new_translation_contributor()` amounts for around 3 seconds of the query time, so this is where we spend the most time. I will be looking into optimising this in #236.

<img width="1563" alt="Screenshot 2024-04-29 at 16 02 27" src="https://github.com/WordPress/wporg-gp-translation-events/assets/550401/e44a5617-e1a7-4d1f-b919-60d69f8cc6aa">


<img width="1553" alt="Screenshot 2024-04-29 at 15 11 44" src="https://github.com/WordPress/wporg-gp-translation-events/assets/550401/a1d3814d-f95b-4cbb-8ca3-e078994c2e4c">

<img width="1568" alt="Screenshot 2024-04-29 at 15 12 07" src="https://github.com/WordPress/wporg-gp-translation-events/assets/550401/76af9d95-8b58-4fe0-85b7-bb3182eb3598">

**Comment by akirk** [comment]
Nice discovery! Here it should actually be enough to add wp_cache calls.

**Comment by psrpinto** [comment]
I guess `wp_cache` calls would work indeed, but I think there are further improvements that can be made if we query for the whole list of contributors ahead of time, instead of doing one query per contributor. The same principle would apply for attendees and hosts.

That's the approach I'm currently exploring in #236, where we would do something like:

- Get list of attendees from database (includes hosts)
- Get list of hosts from the in-memory list of attendees
- Get list of contributors from database
    - The in-memory objects will already tell whether each contributor is a new contributor

Once we have gathered all this information, it is passed to the template, which can then just foreach over the arrays.

**Comment by trymebytes** [comment]
Good one! As you try to improve #236 , please put into consideration, the need to fetch a list of first time contributors. In the future, we would need filters like this(see screenshot below). It would also be nice to be able to have a count of each filter and display. I'm working on this in #233 but would remove some filters for now(to add back in a follow up PR) while we fix the performance issues.
![image](https://github.com/WordPress/wporg-gp-translation-events/assets/2834132/8e1cfa71-a5dc-4f68-9543-1402ca41cb7e)

**Comment by psrpinto** [comment]
> please put into consideration, the need to fetch a list of first time contributors.

Sure thing! I think we have (or will have once currently-open PRs are merged) all the methods needed to retrieve the information for the screenshot above:

- All attendees: `Attendee_Repository::get_attendees()` (introduced by @amieiro in #232 (currently open)
- Hosts: [`Attendee_Repository::get_hosts()`](https://github.com/WordPress/wporg-gp-translation-events/blob/trunk/includes/attendee/attendee-repository.php#L126)
- Non-contributing attendees: `Attendee_Repository::get_attendees_not_contributing()` (introduced in #235, currently open)
- Contributors: `Contributor_Repository::get_contributors()`: (introduced in #235, currently open)

Concerning new translation contributors, I'm planning on implementing this as a flag in the `Contributor` instances, so you can call `$contributor->is_new()`.

>  It would also be nice to be able to have a count of each filter and display.

The methods listed above return an array of objects, so you would be able to do `count( $contributors )`, for example.

Would this address your requirements @trymebytes ?

**Comment by trymebytes** [comment]
Thank you @psrpinto. Though this is not high priority and can be worked on in a future PR - I think it might be helpful to be able to independently fetch the number of attendees, contributors etc without having to fetch the whole list. In the screenshot below, the number of items on each filter will be displayed in the view, irrespective of the filter being used. 

<img width="1477" alt="Screenshot 2024-04-30 at 18 02 24" src="https://github.com/WordPress/wporg-gp-translation-events/assets/2834132/75bec56e-8b3e-4588-bdc1-88db4dc7f1bf">
