### ISSUE TITLE
Make it possible to edit certain fields of a past event

### ISSUE THREAD

**Issue by psrpinto** [WordPress/wporg-gp-translation-events#227]
Before the event has started, the hosts can edit:
- Title
- Description
- Dates

After the event has started but no contributions:
- Title
- Description
- Dates

After the event has started but with contributions:
- Title
- Description
- Extend the end date

1 hour after the event has ended:
- Title
- Description
- Extend the end date

After one hour after the event has ended, they can edit:
- Description

Reflect updates by a message "This event was last updated x minutes ago", linking to [a timeline](https://github.com/WordPress/wporg-gp-translation-events/issues/234).

**Comment by psrpinto** [comment]
Related https://github.com/WordPress/wporg-gp-translation-events/pull/215#discussion_r1572184804

**Comment by akirk** [comment]
@trymebytes  and I discussed that it would be best to implement it by introducing even more custom capabilities, for example `edit_translation_event_title`:
```php
<input
    type="text"
    id="event-title"
    name="event_title"
    value="<?php echo esc_html( $event_title ); ?>"
    required
    size="42"
    <?php echo current_user_can( 'edit_translation_event_title', $event_id ) ?: 'readonly'; ?>
>
```
