### ISSUE TITLE
Hide events

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#230]
For administrators, it should be possible to change the post_status of an event so that unsuitable events can be marked as private or trashed.

On the events list page, there should be a button to hide an event quickly.

Create an admin view of hidden events, so that an event can be restored or fully deleted.

Maybe we can easily also add an edit link (maybe a pencil, and a trash can for deleting).

**Comment by psrpinto** [comment]
Concerning the pencil and trash icons, I opened #247 and will be addressing it separately.
