### ISSUE TITLE
Add is_new_contributor to attendees table 

### ISSUE THREAD

**Issue by psrpinto** [WordPress/wporg-gp-translation-events#241]
@akirk [said](https://github.com/WordPress/wporg-gp-translation-events/pull/236#pullrequestreview-2037997687):

> I think we should consider dropping the `count_translations_before` function and move the `is_new_contributor` value to the `event_attendees` table. This would slightly change the definition of a new contributor, the "new contributor" status is determined when you join an event (vs. right now you could translate yourself out of being a new contributor between the attending click and the event start) but I think that's also valid and would remove these 1.2 seconds off the page load.

**Comment by akirk** [comment]
In our discussion, we considered that the new contributor status should be updated upon the event start. Also, the new contributor status of other upcoming events should be updated in the course of that.

**Comment by psrpinto** [comment]
> the new contributor status should be updated upon the event start

I opened #281 to track this.
