### ISSUE TITLE
Host cannot view attendees after first contribution

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#242]
When an event has started and has at least a contribution, the edit event page where we have  the link to `Manage Attendees` is no longer accessible to the host. 

The manage events page checks for this permission `edit_translation_event` for the page to be accessible but since a contribution has been made, the attendees page is not also available.

Should the `edit_translation_event` permission be modified to allow for the attendees page to be accessible or should we have a new permission for this purpose?

**Comment by akirk** [comment]
Could we also replace the `Edit Event` link with a link to the `Manage Attendees` page after the event has started?

**Comment by trymebytes** [comment]
Yea, sounds good to me.

**Comment by akirk** [comment]
Related to #227.

**Comment by trymebytes** [comment]
We decided to add a new capability.
