### ISSUE TITLE
Fix breadcrumb and css on manage attendees page

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#243]
The breadcrumb on the manage attendees page is broken, does not include the expected links. Also the position of the filters look off on translate.wordpress.org

<img width="1609" alt="image" src="https://github.com/WordPress/wporg-gp-translation-events/assets/2834132/78ba8497-7c95-408e-8999-8ef1ea3c9ba6">

**Comment by akirk** [comment]
Not an issue anymore with the new design.
