### ISSUE TITLE
Enable a wider audience to create events

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#244]
We want to start with allowing GTEs to create events?. This should be implemented in the PR that fixes this issue.

For allowing moderation, can we arbitrarily add people to be allowed to hide and edit events?We need to determine if the right people already have the permission.

**Comment by amieiro** [comment]
I close this issue, as we release the new functionality and we published a P2 about it: [Translation Events: Inviting GTEs to Create and Manage Events](https://make.wordpress.org/polyglots/2024/05/29/translation-events-inviting-gtes-to-create-and-manage-events/)
