### ISSUE TITLE
Nicer error message page

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#251]
In #240, for example, you arrive at a white page with just the error message (because we use `die_with_error`). Two options to fix this:
- Redirect to the Events homepage and add the ability to show a message there
- Show a full page error message with the usual header and footer.

**Comment by amieiro** [comment]
I think we should update the [die_with_error](https://github.com/GlotPress/GlotPress/blob/10644fd9bebd966c1327ff7fea3879556be7833b/gp-includes/route.php#L34) method to show a template and the [die_with_404](https://github.com/GlotPress/GlotPress/blob/10644fd9bebd966c1327ff7fea3879556be7833b/gp-includes/route.php#L324) method to show an improved template.

![image](https://github.com/WordPress/wporg-gp-translation-events/assets/1667814/042087de-1014-4f4d-9ab7-911c862bec82)
