### ISSUE TITLE
Translation action captured twice in stats

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#258]
It appears like we are counting the status change from `current` to `old` in the stats. To reproduce;
- Join an event as a GlotPress validator
- Go to a current GlotPress project and update the translation for a current translation and save ,  you would notice that the count for `created` in the stats table is increased by 2 instead of 1.
<img width="1213" alt="Screenshot 2024-05-08 at 15 50 58" src="https://github.com/WordPress/wporg-gp-translation-events/assets/2834132/c5826617-f7cd-4ca4-85f4-991481019008">

**Comment by akirk** [comment]
I've closed #158 since this reported the same behavior.
