### ISSUE TITLE
Merge the type of events in the "My events" page

### ISSUE THREAD

**Issue by amieiro** [WordPress/wporg-gp-translation-events#270]
At https://github.com/WordPress/wporg-gp-translation-events/pull/260#issuecomment-2104579684 we decided to merge the type of events in the "My events" page using tags:
- Will attend. For future events.
- Attending. For current events.
- Attended. For past events.

Current template

![image](https://github.com/WordPress/wporg-gp-translation-events/assets/1667814/50af6ff8-c339-421a-843d-259f3b6b0de9)

Proposed template (removing categories, using only tags)

![image](https://github.com/WordPress/wporg-gp-translation-events/assets/1667814/b76bcdb6-3b22-4076-9531-650f945c1b6f)

**Comment by psrpinto** [comment]
We have now [deciced](https://github.com/WordPress/wporg-gp-translation-events/pull/260#issuecomment-2104726301) to show a single list, but add tags to entries on the list:

- "Will attend": For future events
- "Attending": For current events
- "Attended": For past events
