### ISSUE TITLE
Recalculate is_new_contributor upon event start

### ISSUE THREAD

**Issue by psrpinto** [WordPress/wporg-gp-translation-events#281]
Extracted from #241, suggested by @akirk 

The new contributor status should be updated upon the event start. Also, the new contributor status of other upcoming events should be updated in the course of that.

**Comment by psrpinto** [comment]
I can't recall what was the reasoning for doing this, could you provide more information about this @akirk ?

**Comment by akirk** [comment]
Let's say, you're new to WordPress.org and pledge to attend a translation event in 2 months. You'll get the new contributor flag. Now you start translating before the event starts. You're no longer a new contributor.
