### ISSUE TITLE
Sort past events on the homepage in ascending order

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#287]
The past events on the events homepage are sorted in descending order, as shown below;

<img width="1073" alt="image" src="https://github.com/WordPress/wporg-gp-translation-events/assets/2834132/ba7c5482-be8d-49ea-8c22-575171870ee0">

We need to sort them in ascending order, that's from the recently ended to the long-concluded events.

**Comment by psrpinto** [comment]
Fixed in https://github.com/WordPress/wporg-gp-translation-events/pull/319

**Comment by psrpinto** [comment]
Fixed in https://github.com/WordPress/wporg-gp-translation-events/pull/319
