### ISSUE TITLE
In events time line there should be exact date and time stamp

### ISSUE THREAD

**Issue by DivyarajChudasama** [WordPress/wporg-gp-translation-events#288]
![rtcamp](https://github.com/WordPress/wporg-gp-translation-events/assets/92981225/dfa92600-3147-4bfb-b780-41a8139f2920)

**Currently in all the events, its just displaying the weeks, not the exact date and time**

**Comment by psrpinto** [comment]
Thanks for reporting this. It makes sense indeed to display the exact date and time in the event list. We will be addressing this issue.
