### ISSUE TITLE
Ignore "mark as fuzzy" actions

### ISSUE THREAD

**Issue by psrpinto** [WordPress/wporg-gp-translation-events#29]
Currently `mark_fuzzy` is being tracked and is included in the "Translations reviewed" stat, along with `approve`, `reject` and `request_changes`.

If I understood correctly, @amieiro mentioned that "Mark as fuzzy" might be used as "postponing" the review of the translation to the future, and that it is in practice the same as leaving the translation in the Waiting queue.

So should we:

1. Track it in the database table, and include it in the stats under "Translations reviewed"? (how it works today)
2. Track it in the database table, but don't include it in the stats? (useful if we think we might change our mind later and want to start including it in the stats)
3. Don't track it in the database table.

@amieiro @akirk @trymebytes

**Comment by akirk** [comment]
My vote goes to not a review action. Don't track its stats.
