### ISSUE TITLE
Event waiting stats with zero items link to blank page

### ISSUE THREAD

**Issue by pedro-mendonca** [WordPress/wporg-gp-translation-events#291]
The event waiting stats with 0 (zero) count is linking to a blank page.
If stats is 0, doesn't even need a link.

https://translate.wordpress.org/events/2024/wordcamp-porto-portugal-2024-contributor-day/

![imagem](https://github.com/WordPress/wporg-gp-translation-events/assets/7371591/6a4ce753-eae0-4008-bbaf-2735a1d4af52)

**Comment by amieiro** [comment]
This issue was solved on #290, so I am going to close it. Thank you for reporting it.
