### ISSUE TITLE
Sync Post Date with Event Start Meta

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#292]
We need to do a [meta query to sort events by start date](https://github.com/WordPress/wporg-gp-translation-events/pull/283/files#diff-1712abbd3f74733940f992320a969c855bae5ffa5b7488460bad7394b94d082fR231-R235). Since we're not using the post date anyway, I think it'd be good if we'd use this as an even start in favor of a meta value.

This would allow us to sort events by post date.

**Comment by trymebytes** [comment]
I think the post date currently helps us track the event creation date, will this change mean we won't be able to tell the date an event was created?

**Comment by akirk** [comment]
Not necessary to change this at the moment.
