### ISSUE TITLE
When a user creates an event, they are no longer automatically added as an attendee

### ISSUE THREAD

**Issue by psrpinto** [WordPress/wporg-gp-translation-events#301]
Steps to reproduce:

1. Create an event by publishing directly (don't make it a draft first)
2. Go to the event details page for that event
3. You see the "Attend Event" button instead of seeing "You're attending"
4. There is no entry in the attendees table for that event

**Comment by psrpinto** [comment]
The issue is [here](https://github.com/WordPress/wporg-gp-translation-events/blob/trunk/wporg-gp-translation-events.php#L289).

**Comment by akirk** [comment]
Let's leave it like this for now since we cannot know if the user is a remote attendee or not. So they can manually attend after creating it.
