### ISSUE TITLE
What to display when there are no new events

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#312]
When there are no current or upcoming events, this is how it's displayed(see screenshot) and it may be a little confusing.

<img width="1512" alt="Screenshot 2024-05-29 at 10 47 01" src="https://github.com/WordPress/wporg-gp-translation-events/assets/2834132/b7c10c7c-c828-4119-b6ed-3dd94fd87e15">

Should we reword the text "No events found" to "No current and upcoming events found"? Or should we show the headings "Upcoming Events" and Current Events", see mockup below.

<img width="1516" alt="image" src="https://github.com/WordPress/wporg-gp-translation-events/assets/2834132/951a23b6-bfab-431e-b61d-b98211346b6a">

**Comment by akirk** [comment]
This is now implemented like this:
![Image](https://github.com/user-attachments/assets/669d7dbc-e8de-43f5-ad21-a2ff3481c42c)
