### ISSUE TITLE
Flag for remote event

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#335]
We could consider adding an icon to the titles of remote events on the homepage to distinguish them easily. See mockup below;

<img width="960" alt="Screenshot 2024-07-12 at 13 31 20" src="https://github.com/user-attachments/assets/6221ec35-51ad-4aee-b0dc-f391f36f0ca1">

**Comment by akirk** [comment]
Great! What about we do this in the course of transitioning the list views to the block theme?

**Comment by trymebytes** [comment]
Yes, sounds good to me!

**Comment by akirk** [comment]
Completed in #370.
