### ISSUE TITLE
Social Sharing is broken because of robots.txt

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#356]
We need Social networks to access these URLs despite everything else on translate.wordpress.org not being indexable:
See https://translate.wordpress.org/robots.txt

![Screenshot 2024-09-17 at 17 30 22](https://github.com/user-attachments/assets/afd112fc-3a74-47f6-9ec4-b51073dce7cc)

Thanks @alexdeborba for reporting!

**Comment by akirk** [comment]
https://github.com/WordPress/wordpress.org/blob/trunk/wordpress.org/public_html/wp-content/mu-plugins/pub/wporg-robots.php needs to be updated to allow `/events/`

**Comment by amieiro** [comment]
I have checked with the [Sharing Debugger](https://developers.facebook.com/tools/debug/) from Facebook, and it is working:

![Image](https://github.com/user-attachments/assets/e0f0b038-4ed7-4aa4-85a4-529631a932c4)
