### ISSUE TITLE
Should events be createable/editeable through wp-admin?

### ISSUE THREAD

**Issue by psrpinto** [WordPress/wporg-gp-translation-events#40]
We briefly discussed this before but I'm not sure we reached a conclusion, so I'm opening an issue.

Currently events can be created or edited through either the custom pages in this plugin, or through wp-admin, as any other post. However, AFAICT, currently some things are only done when the event is edited through this plugin.

Examples are validating that the end is after the start, or invalidating the active events cache.

I see two options here:

1. Prevent events from being created/edited through wp-admin. Not sure that's a very WordPress-y thing to do.
2. Fully support creating/editing events through wp-admin (e.g. validate end is after start, invalidate cache, etc)

**Comment by amieiro** [comment]
I think we should implement the second option, and only the admins should have permission to do this. Some use cases:
- To delete spam events.
- To update the details of an event created by a user who cannot be contacted.

**Comment by akirk** [comment]
We decided we'll hide the admin UI for now.
