### ISSUE TITLE
Sorting events on the events page

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#46]
This issue is opened as a follow up to [this comment](https://github.com/WordPress/wporg-gp-translation-events/pull/36#issuecomment-1936227058);

Should we sort events based on their start dates or end dates. Sorting by event start dates means only events starting on the current date or later will be included in the list.

The issue with this is that, events that last for several days will not be included once their start date has passed the current date, thereby reducing visibility for such events.

**Comment by psrpinto** [comment]
I think maybe what we could is to have two sections, "Active events" and "Upcoming events".

The active events could then be calculated in [the same way as we do for storing stats](https://github.com/WordPress/wporg-gp-translation-events/pull/35): start is before `now + d` (where `d` is something like 1h) AND end is after `now`. This would give you events that are active in the next hour.

The upcoming events list would then exclude the active events, and could be sorted by start date.
