### ISSUE TITLE
Create a custom post type which is a new translation event

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#5]
To create a new self-serve translation event, a new post which uses the custom post type will be created.
The post_content will hold the event description
The post_meta for restrictions like locale, date, projects

Here are some of the comments from the old repo;

**Comments:**
@trymebytes: I think we should an input field for event address as not all events would be online.
@akirk: Maybe it could rather be solved with tags down the line?
 @psrpinto:  Something that might be worth considering here, is that I think we need to store the timezone of the event. See https://github.com/WordPress/wporg-gp-translation-events/issues/4#issuecomment-1895519695 for more context.
@amieiro: We have https://events.wordpress.org/ in beta version, so if we are going to include these events there, we should take a look at their database format to make our events compatible with theirs.

**Comment by psrpinto** [comment]
I think this one has already been addressed, right @trymebytes? Or is there something that remains to be done?
