### ISSUE TITLE
Add a "Edit" link in the event page

### ISSUE THREAD

**Issue by amieiro** [WordPress/wporg-gp-translation-events#56]
We need to add two links ("Edit" and "Delete") if the current user is an admin or the event creator in the events list.

![image](https://github.com/WordPress/wporg-gp-translation-events/assets/1667814/6f23977d-d437-42fd-9f2b-1bd6980b0c13)

**Comment by trymebytes** [comment]
Nice! I wonder if this should be added to the list of events in the `My Events` section when developed.

**Comment by amieiro** [comment]
> Nice! I wonder if this should be added to the list of events in the `My Events` section when developed.

Yes, I think we should add the same links in the `My Events` page referenced [here](https://github.com/WordPress/wporg-gp-translation-events/issues/57), but not in the right sidebar, in the `Events I'm Attending`, because this section is only a list with the titles of the events.

**Comment by akirk** [comment]
The scope of this has been changed so that the events page gets the links when you are allowed to do so.

**Comment by trymebytes** [comment]
Closing this in favour of https://github.com/WordPress/wporg-gp-translation-events/issues/57
