### ISSUE TITLE
Display stats in event page

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#6]
The event page should contain stats from the event, stats like;

- number of attendees
- number of strings translated in total
- number of translations approved
- number of translations by locale

**Comment by psrpinto** [comment]
Concerning how stats should be displayed, as discussed in a meeting:

Stats are displayed as a table, with a row per locale, a final *Total* row, and three columns:

- Number of translations created
- Number of translations reviewed (approved, rejected, etc)
- Number of contributors

The *Total* row displays the sum of the columns. For the total number of contributors, it should count unique users.

Example:

| Locale | Translations created | Translations reviewed | Contributors |
| ---- | ---- | ---- | ---- |
| pt | 365 | 243 | 42 |
| es | 456 | 653 | 78 |
| **Total** | **821** | **896** | **100** |

There should also be a sentence that can be copy-pasted, for example:

> At WordCamp Asia, 821 translations were created and 896 were reviewed. 100 contributors participated in this translation event.
