### ISSUE TITLE
Add Events link to the header on translate.w.org

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#61]
We need to add a link to the header on translate.wordpress.org, see mockup below;
<img width="1672" alt="Screenshot 2024-02-13 at 10 22 20" src="https://github.com/WordPress/wporg-gp-translation-events/assets/2834132/5ab6ce0a-063e-4b00-b7dd-d3d774516fd6">

**Comment by amieiro** [comment]
Is this  menu hard-coded in a plugin, or is it in a menu, so we can add an item using the UI?

**Comment by trymebytes** [comment]
It doesn't appear to be hardcoded, looks like it's in a menu added in the admin backend.

**Comment by psrpinto** [comment]
Closing in favour of #109.
