### ISSUE TITLE
Improve View Event visually

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#65]
### Description
- [ ] Allow rendering of HTML tags like in posts, i.e. use `wp_kses_post`.

### Attend

- [x] Make the position of the Attend button independent of whether the event has a description.

### Stats
- [x] Change the CSS so that the table looks visually more appealing, maybe restructure it to not use a table?
- [ ] Possibly multiple views of the stats: one per locale, one per type of contribution
- [x] Copy & pastable text that includes the most importat stats: At the xyz event, 3 people contributed in 3 languages (ab, cd, ef), translated x strings and reviewed y strings.

### If it's your own Event
- [x] Add an Edit Button

**Comment by trymebytes** [comment]
The `Allow rendering of HTML tags like in posts, i.e. use wp_kses_post.` task has been fixed in #76
