### ISSUE TITLE
Prevent Fatal when invalid date is given

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#71]
Even if the invalid date should not happen, we should not fatal on it when editing the event:

![Screenshot 2024-02-14 at 11 29 21](https://github.com/WordPress/wporg-gp-translation-events/assets/203408/308190f3-66c3-4ea4-9716-a104b8c45fa5)

**Comment by trymebytes** [comment]
Could you please explain how to reproduce this?

**Comment by psrpinto** [comment]
Since this is about an uncaught exception, and we have #129, I'm closing this one in favour of #129.
