### ISSUE TITLE
Translation stats collected from each user 

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#8]
For attendees that have opted in, we'll collect the following information about their translation work;

- reviewed strings (current / rejected)
- new translations (waiting / current)
- approved translations (current)

**Comment by psrpinto** [comment]
I'm a bit confused about this issue. Is this about storing the stats (in which case would it be a duplicate of #7), or is it about displaying stats of a given user?

**Comment by akirk** [comment]
This is now implemented.
