### ISSUE TITLE
Don't get a prompt when you publish a draft event

### ISSUE THREAD

**Issue by amieiro** [WordPress/wporg-gp-translation-events#81]
If you save the draft, and then you publish the event, you get a prompt. We can address this issue in another PR.

**Comment by trymebytes** [comment]
On testing in the current version of the trunk branch, this is no longer the case, can we close this?

**Comment by amieiro** [comment]
I have just tested, and we go on having this problem. To try to reproduce:
- You create a new draft.
- You update the event.
- You publish the event. At this time, I don't get the publishing prompt.
